CREATE TABLE `sap_measuring_point_header_data`
(
  `MeasuringPoint`                    varchar(12) NOT NULL,
  `MeasuringPointDescription`         varchar(40) DEFAULT NULL,
  `MeasuringPointObjectIdentifier`    varchar(20) DEFAULT NULL,
  `TechnicalObjectType`               varchar(10) DEFAULT NULL,
  `MeasuringPointPositionNumber`      varchar(20) DEFAULT NULL,
  `MeasuringPointCategory`            varchar(1) DEFAULT NULL,
  `CreationDate`                      varchar(80) DEFAULT NULL,
  `LastChangeDate`                    varchar(80) DEFAULT NULL,
  `MeasuringPointIsCounter`           tinyint(1) DEFAULT NULL,
  `MsrgPtInternalCharacteristic`      varchar(10) DEFAULT NULL,
  `CharcValueUnit`                    varchar(3) DEFAULT NULL,
  `MeasuringPointDecimalPlaces`       varchar(16) DEFAULT NULL,
  `MeasuringPointExponent`            varchar(16) DEFAULT NULL,
  `MeasuringPointCodeGroup`           varchar(8) DEFAULT NULL,
  `ValuationCodeIsSufficient`         tinyint(1) DEFAULT NULL,
  `Assembly`                          varchar(40) DEFAULT NULL,
  `MeasuringPointIsInactive`          tinyint(1) DEFAULT NULL,
  `MeasuringPointShortText`           varchar(40) DEFAULT NULL,
  `MeasurementRangeUnit`              varchar(3) DEFAULT NULL,
  `MsmtRdngSourceMeasuringPoint`      varchar(12) DEFAULT NULL,
  `MeasuringPointTargetValue`         float(30) DEFAULT NULL,
  `MeasuringPointMaximumThreshold`    float(30) DEFAULT NULL,
  `MeasuringPointMinimumThreshold`    float(30) DEFAULT NULL,
  `MeasuringPointAnnualEstimate`      float(30) DEFAULT NULL,
  `CounterOverflowRdngThreshold`      float(30) DEFAULT NULL,
  `MsrgPtIsCountingBackwards`         tinyint(1) DEFAULT NULL,
  `MeasurementTransferIsSupported`    tinyint(1) DEFAULT NULL,
  `FunctionalLocation`                varchar(30) DEFAULT NULL,
  `Equipment`                         varchar(18) DEFAULT NULL,
  `MsmtRdngTransferMode`              varchar(1) DEFAULT NULL,
    PRIMARY KEY (`MeasuringPoint`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
